import Head from 'next/head'
import {useRouter} from 'next/router'
import styles from '../../styles/Home.module.css'
import {list} from '../../dados'

export default function Detalhe() {

  const router = useRouter()
  const id = router.query.id
  const info = list.filter((nome)=>nome.id === parseInt(id))
  

    return ( 
    <div className = { styles.container } >
        <Head >
        <title > Create Next App </title> < meta name = "description" content = "Generated by create next app" / >
        <link rel = "icon" href = "/favicon.ico" / >
        </Head>

        { info.map(i=>(
        <div className={styles.main} key={i.id}>
        <div className={styles.card}>
            <img  src={i.img} className={styles.cursoimg} />
            <div className={styles.cursoinfo}>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
            </div>
            <div className={styles.cursopreco}>
                <span className={styles.precode}>R$80,00</span>
                <span className={styles.precopor}>R$50,00</span>
            
            </div>
        </div>
        <div className={styles.cardLeft}>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
                <h4 className={styles.cursoinfoh4}>Bolos deliciosos direto na sua casa</h4>
                <p>{i.nome}</p>
            </div>
        
         
     </div>
          ))}
          

        </div>
    )
}

