import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Detalhe({info}) {
    return ( 
    <div className = { styles.container } >
        <Head >
        <title > Create Next App </title> < meta name = "description" content = "Generated by create next app" / >
        <link rel = "icon" href = "/favicon.ico" / >
        </Head>
            <h1>teste</h1>
            <ul>
            <li>
                {info.nome}
             
              <Image
                  src={info.img}
                  alt="My Image"
                  width={400}
                  height={400}

              />
            
             </li>

            </ul>

        </div>
    )
}

export async function getServerSideProps(context){
  const res = await fetch(`https://cardapio-pdzzd39f0-cleriston1202.vercel.app/api/detalhe/${context.params.id}`) 
  const dados = await res.json()


  return {
    props: {
      info: dados
    }
  }
}