import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
         <ul>
           {list.map(item=>(
            
             <li key={item.id}>{item.nome}
             <a href={`/detalhe/${item.id}`}>
              <Image
                  src={item.img}
                  alt="My Image"
                  width={300}
                  height={300}

              />
              </a>
             </li>
           ))}
         </ul>
        </div>
      </main>
    </div>
  )
}
export async function getServerSideProps(){
  const res = await fetch("http://localhost:3000/api/detalhe/cake") 
  const dados = await res.json()


  return {
    props: {
      list: dados
    }
  }
}