import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home({list}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {list.map(item=>(
      <div className={styles.curso} key={item.id}>
            <img  src={item.img} className={styles.cursoimg} />
            <div className={styles.cursoinfo}>
                <h4 className={styles.cursoinfoh4}>Docker: Ferramenta essencial para Desenvolvedores</h4>
                <p>{item.nome}</p>
            </div>
            <div className={styles.cursopreco}>
                <span className={styles.precode}>R$80,00</span>
                <span className={styles.precopor}>R$50,00</span>
                <a href={`/detalhe/${item.id}`} >Read more</a>
            </div>
        </div>
        ))}
      
      
  </div>
  

       
  )
}
export async function getServerSideProps(){
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/detalhe/cake`) 
  const dados = await res.json()


  return {
    props: {
      list: dados
    }
  }
}