import Head from 'next/head'
import Image from 'next/image'
import {
  Card, CardImg, CardText, CardBody,CardDeck,
  CardTitle, CardSubtitle, Container, Row, Col, Button
} from 'reactstrap';

import 'bootstrap/dist/css/bootstrap.min.css';
import styles from '../styles/Home.module.css'


export default function Home({list}) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <Row>
           <div  className={styles.grid}>
      
            {list.map(item=>(
              <Col >
               <div className={styles.card}  key={item.id}>
            <div className="card" >
              <img className="card-img-top" src={item.img} alt="Card image cap"/>
              <div className="card-body">
                <h5 className="card-title">{item.nome}</h5>
                <p classNameName="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href={`/detalhe/${item.id}`} className="btn btn-primary">Go somewhere</a>
              </div>
            </div>
            </div>
            </Col>
            ))}
       
       </div>
       </Row >
       </Container>
  )
}
export async function getServerSideProps(){
  const res = await fetch("http://localhost:3000/api/detalhe/cake") 
  const dados = await res.json()


  return {
    props: {
      list: dados
    }
  }
}